targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: event_hub|lib/api/graphql/schema.graphql

      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: event_hub|lib/api/graphql/schema.graphql






# targets:
#   $default:
#     builders:
#       gql_build|schema_builder:
#         enabled: true
#       gql_build|ast_builder:
#         enabled: true
#       gql_build|data_builder:
#         enabled: true
#         options:
#           schema: event_hub|lib/api/graphql/schema.graphql
#       gql_build|var_builder:
#         enabled: true
#         options:
#           schema: event_hub|lib/api/graphql/schema.graphql
#       gql_build|serializer_builder:
#         enabled: true
#         options:
#           schema: event_hub|lib/api/graphql/schema.graphql

#       ferry_generator|req_builder:
#         enabled: true
#         options:
#           schema: event_hub|lib/api/graphql/schema.graphql
        