name: event_hub
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^0.3.3
  auto_route: ^3.2.4
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  ferry: ^0.10.4
  ferry_flutter: ^0.5.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4
  flutter_native_splash: ^2.1.6
  flutter_riverpod: ^1.0.4
  flutter_svg: ^1.0.3
  flutter_zoom_drawer: ^3.0.2
  geolocator: ^8.2.1
  google_fonts: ^2.3.2
  google_maps_flutter: ^2.1.6
  gql_http_link: ^0.4.1
  hidden_drawer_menu: ^3.0.1
  hooks_riverpod: ^1.0.4
  image: ^3.1.3
  image_picker: ^0.8.5
  image_picker_for_web: ^2.1.6
  nb_utils: ^4.4.17
  readmore: ^2.1.0
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2

dependency_overrides:
  analyzer: ^3.4.1
  gql: 0.13.0

dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.5
  ferry_generator: 0.4.4

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboard/
    - assets/icons/
    - assets/images/
    - assets/icons/menu_items_icons/

  fonts:
    - family: Cereal
      fonts:
        - asset: assets/fonts/AirbnbCerealMedium.ttf
          weight: 400
        - asset: assets/fonts/AirbnbCerealLight.ttf
          weight: 100
        - asset: assets/fonts/AirbnbCerealBook.ttf
          weight: 300
        - asset: assets/fonts/AirbnbCerealBold.ttf
          weight: 600
        - asset: assets/fonts/AirbnbCerealExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AirbnbCerealBlack.ttf
          weight: 900
    - family: EventHub
      fonts:
        - asset: assets/fonts/EventHub.ttf
